version: "3.9"

services: 
  web: 
    container_name: django-pybo
    build: .
    command: >
        bash -c "python manage.py makemigrations 
        && python manage.py migrate
        && python manage.py collectstatic --noinput 
        && gunicorn --bind 0:8000 config.wsgi:application" 
    volumes: 
      - .:/pybo-docker
    ports: 
      - "8000:8000" 
  
  proxy: 
    container_name: proxy-pybo
    image: nginx:latest
    ports: 
      - "80:80"
    volumes: 
      - .:/pybo-docker 
      - .:/etc/nginx/conf.d
    depends_on: 
      - web

