version: "3.9"

services: 
  web:
    build: .
    command: find . -path '"*/migrations/*.py"' -not -name '"__init__.py"' -delete
    command: find . -path '"*/migrations/*.pyc"' -delete
    command: >
        bash -c "rm -rf db.sqlite3 
        && python manage.py makemigrations 
        && python manage.py migrate 
        && gunicorn --bind 0:8000 config.wsgi:application"
    ports: 
      - "8000:8000"

