name: test

on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches: 
      - master

jobs: 
  docker: 
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start continers
        run: docker-compose up -d --build

      - name: Stop containers
        if: always()
        run: docker-compose down
